### PR TITLE
feat: Add SBOM to main cloudbuild

### PR DESCRIPTION
**Pull request by LilaKelland**
Added SBOM generation to the main cloudbuild (on the main branch).  It then saves the SBOM to a bucket in the Safe Inputs project.  

Have also added a 'devsecops' folder to store CI/ devsecops related docs and code. (i.e. the cloud function in https://github.com/HC-IPPM/safe-inputs/pull/82), but right now, in this branch, it only contains SBOM READMEs.

Note - I've successfully run this when it was pointing to a bucket in my project.  Have it now pointed it to the bucket in the Safe Inputs project, but when it's pointed to the Safe Inputs project, and  triggered locally, it's uses my project's compute@developer service account, which doesn't have permission to the Safe Inputs project, so fails with a "does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist)." error.  I've given the cloud build service account the object create role (https://github.com/PHACDataHub/acm-core/pull/374/files) - hopefully this will work through the GitHub trigger/ using Safe Inputs cloudbuild service account, and doesn't also need the storage objects list separate access.

### CODE REVIEW

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]
Does the storage bucket have appropriate bucket-level permissions to allow the service account to write to it? The cloud build service account should only have `roles/storage.objectCreator` on the bucket, not the project. I don't have permissions to view the bucket level IAM right now to look at that :laughing: 

I'm going to toss review over to @vedantthapa, I'd like him to help make sure the new bucket is part of our IaD. Now that he's back, please catch him up on any infrastructure you've made with click-ops in the meantime!

Otherwise, looks good, thanks!

**Review by vedantthapa — APPROVED** [review]
LGTM, thanks!

Do you think it might be worth configuring lifecycle management policies for the objects in a separate PR?

Also, I had added some setup instructions and info about IaD definitions [here](https://github.com/HC-IPPM/safe-inputs/tree/main/kubernetes#setup), we could consider moving relevant bits from it under the `Infrastructure as Code` section of the devsecops README, what do you think?

**Comment by LilaKelland** [comment]
Sounds like a good plan.  What sort of lifecycle should these have?  

Welcome back Vedant! 

Only click-opsing/ gclouding in my project -  using acm-core for Safe-Inputs (though, @vedantthapa, have questions for you around resources for a separate PR later).

**Review by Stephen-ONeil — APPROVED** [review]
:+1:

**Comment by vedantthapa** [comment]
> Sounds like a good plan. What sort of lifecycle should these have?
> 
> Welcome back Vedant!
> 
> Only click-opsing/ gclouding in my project - using acm-core for Safe-Inputs (though, @vedantthapa, have questions for you around resources for a separate PR later).

Thanks Lila! 

Regarding lifecycle rules, it's mostly related to cleaning up to save costs. While it would depend on our regulatory requirements and what we (or security) are planning to do with it, I believe given that it's generated on every PR to main (multiple times a day due to renovate) cleaning up anything older than 30d should be fine for now?

**Pull request merged**
